language: c

sudo: false

addons:
  apt:
    packages:
      - bison
      - dejagnu
      - dnsutils
      - gettext
      - keyutils
      - ldap-utils
      - libldap2-dev
      - libkeyutils-dev
      - libssl-dev
      - slapd
      - tcl-dev
      - tcsh

compiler:
  - clang
  - gcc

script: cd src && autoreconf && ./configure --with-ldap && make && make check
